story8/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story8app.urls')),
    path('story9app/', include('story9app.urls')),
]

story8app/urls.py
from django.conf.urls import url, include
from django.urls import path
from . import views

app_name = 'story8'
urlpatterns = [
    path('', views.book_func, name = 'book_func'),
    path('jsonreq/<str:book>', views.jsonreq_func, name = 'jsonreq_func')
]

story9app/urls.py
from django.urls import path
from . import views

app_name = "story9app"

urlpatterns = [
    path('acc', views.account, name="acc"),
    path('login', views.log_in, name="login"),
    path('logout', views.log_out, name="logout")
]

story8app/models.py
from django.db import models

# Create your models here.

story9app/models.py
from django.db import models

# Create your models here.

story8app/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
import json
import requests

def book_func(request):
    return render(request, 'story8.html')

def jsonreq_func(request, book):
    response = requests.get('https://www.googleapis.com/books/v1/volumes?q=' + book)
    return JsonResponse(response.json())

story9app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def account(req):
    error = "Username atau Password anda salah"
    user = req.user
    if user.is_authenticated:
        return redirect('story9app:login')
    if req.method == 'POST':
        form = AuthenticationForm(data=req.POST)
        if form.is_valid():
            user = form.get_user()
            login(req, user)
            return redirect('story9app:login')
    else:
        form = AuthenticationForm()
    return render(req, 'accounts.html', {'form':form, 'error':error})

def log_in(req):
    return render(req, 'login.html')

def log_out(req):
    logout(req)
    return redirect('story9app:acc')

story8app/templates/story8.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Book Finder</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/bookstyle.css' %}">
  <script type="text/Javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>
<body>
  <div class="container">
      <h1>Welcome to Book Finder!</h1>
    <input class="searchbar" type="text" placeholder="Search here"> <button class="btn btn-dark" type="submit" name="button">Search</button>
    <div>
      <table class="table table-light">
        <thead>
          <tr>
            <th scope="col">No</th>
            <th scope="col">Cover</th>
            <th scope="col">Title</th>
            <th scope="col">Author</th>
            <th scope="col">Publisher</th>
            <th scope="col">Published Date</th>
          </tr>
        </thead>
        <tbody id="content">
        </tbody>
      </table>
    </div>
  </div>
  <script src="{% static 'js/myscript.js' %}" charset="utf-8"></script>
</body>
</html>

story9app/templates/accounts.html
{% load static %}
<head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <title>Search Book Engine</title>
        <style>
        body {
            font-family: 'Nunito', sans-serif !important;
            background: aquamarine;
            }
        </style>
</head>

{% block content %}
<div class="text-center" style="margin-top: 30px;">
    {% if form.errors %}
    {{error}}
    {% endif %}
    <form method="POST" action='{% url "story9app:acc" %}'>
        {% csrf_token %}
        <label>Username</label>
        <br>
        {{ form.username }}
        <br>
        <label>Password</label>
        <br>
        {{ form.password }}
        <br>
        <input type="submit" value="Log in" class="button">
    </form>
</div>
{% endblock %}

story9app/templates/login.html
{% load static %}

{% load static %}
<head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <title>Search Book Engine</title>
        <style>
        body {
            font-family: 'Nunito', sans-serif !important;
            background: aquamarine;
            }
        </style>
</head>

{% block content %}

<div class="text-center" style="margin-top: 30px;">
    {% if user.is_authenticated %}
    <h1>Welcome, {{user}}</h1> 
    <a href="{% url 'story9app:logout' %}">
        <div class='logout'>
            log out
        </div>
    </a>
    {% else %}
    <a href="{% url 'story9app:acc' %}">
        <div class='login'>
            log in
        </div>
    </a>
    {% endif %}

</div>
{% endblock %}